version: "3.9"

services:
  backend:
    container_name: callix-challenge-backend
    image: callix-challenge-backend
    build:
      dockerfile: Dockerfile
      context: ./backend/
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    networks:
      - callix-challenge

  frontend:
    container_name: callix-challenge-frontend
    image: callix-challenge-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    ports:
      - 80:80
    env_file:
      - ./frontend/.env
    environment:
      REACT_APP_SPACEX_API_URL: "http://backend:3000/"
    networks:
      - callix-challenge

networks:
  callix-challenge:
