openapi: 3.0.2
info:
  title: Microservice Codebase
  version: '1.0'
servers:
  - url: http://localhost:3000
    description: Development
  - url: https://callix-challenge-2.herokuapp.com/
    description: Production

paths:
  /health:
    get:
      description: This route returns status of service and sub-services.
      summary: Route to check service health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: ok
        '500':
          description: Internal Sever Error
  /launches/next:
    get:
      description: This route returns status of service and sub-services.
      summary: Route to check service health
      responses:
        '200':
          description: OK
        '500':
          description: Internal Sever Error
  /launches/last:
    get:
      description: This route returns status of service and sub-services.
      summary: Route to check service health
      responses:
        '200':
          description: OK
        '500':
          description: Internal Sever Error
  /launches/upcoming:
    get:
      description: This route returns status of service and sub-services.
      summary: Route to check service health
      responses:
        '200':
          description: OK
        '500':
          description: Internal Sever Error
  /launches/past:
    get:
      description: This route returns status of service and sub-services.
      summary: Route to check service health
      responses:
        '200':
          description: OK
        '500':
          description: Internal Sever Error
